Changes according to meeting on the 7th of December 2021.
stadlar/IST-FUT-FMTH pull request #128
Opened 2021-12-13 14:20 UTC by gudmundurjon

2021-12-15 14:53 UTC, gudnithor requested changes
Það þarf að vinna þessa PR betur - ég er ekki búinn og bara rétt að byrja.

(Það hefði verið fínt að hafa sér PR fyrir hvert issue, það auðveldar mjög yfirferðina).

2021-12-15 14:53 UTC, gudnithor commented on Vinnusvæði/Verkþáttur 4/IOBWS-Claims3.0.yaml
> +    patch:
Af hverju ekki að taka út PUT samkvæmt því sam var ákveðið í #76 á síðasta fundi?

2021-12-15 14:53 UTC, gudnithor commented on Vinnusvæði/Verkþáttur 4/IOBWS-Claims3.0.yaml
> +        - $ref: "#/components/parameters/X-Idempotency-Key"
Ég man ekki hvar við enduðum með X-Idempotency-Key umræðuna. Ætluðum við að taka það út eða átti VH5 að taka ákvörðun um það?

2021-12-15 14:53 UTC, gudnithor commented on Vinnusvæði/Verkþáttur 4/IOBWS-Claims3.0.yaml
> +          $ref: "#/components/responses/OK_200_ClaimResponseInformation"
Það þarf að lagfæra þetta, þetta er return object úr gömlu batch aðgerðunum fyrir breytingu? Þetta ætti að skila kröfu hlutnum eins og hann lítur út eftir breytinguna.

2021-12-15 14:53 UTC, gudnithor commented on Vinnusvæði/Verkþáttur 4/IOBWS-Claims3.0.yaml
> +        then submitted and amended according to new information.
```suggestion
        Existing claim is patched according to the instructions sent in the body. See RFC-6902 for the implementation of the patch body.
```

2021-12-15 14:53 UTC, gudnithor commented on Vinnusvæði/Verkþáttur 4/IOBWS-Claims3.0.yaml
> +      - "LegalCollection"
Hér vantar "WaitingForSecondary" - sjá niðurstöðu í issue #82.

2021-12-15 14:53 UTC, gudnithor commented on Vinnusvæði/Verkþáttur 4/IOBWS-Claims3.0.yaml
> +  /v1/claims/{claimId}/primary:
Þetta er ekki eins og var rætt um í #82 - þar átti þetta að heita /collection?

2021-12-15 14:53 UTC, gudnithor commented on Vinnusvæði/Verkþáttur 4/IOBWS-Claims3.0.yaml
> +          maxLength: 200
Úr issue #123: _"Hendum billPresentmentSystem og bætum við svæðinu additionalInformation."_

2021-12-16 15:18 UTC, gudmundurjon commented on Vinnusvæði/Verkþáttur 4/IOBWS-Claims3.0.yaml
> +        - $ref: "#/components/parameters/X-Idempotency-Key"
VH5 ætlaði að nota okkar vinnu við sýna vinnu. Þannig að X-Idempotency-Key er inn.

2021-12-16 15:20 UTC, gudmundurjon commented on Vinnusvæði/Verkþáttur 4/IOBWS-Claims3.0.yaml
> +    patch:
Rétt, PUT fer út, kemur í næsta check-in. Ein spurning varðandi patch viljum við nota options samhliða?

2021-12-16 15:20 UTC, gudmundurjon commented on Vinnusvæði/Verkþáttur 4/IOBWS-Claims3.0.yaml
> +          $ref: "#/components/responses/OK_200_ClaimResponseInformation"
Góður punktur, verður lagað.

2021-12-16 15:22 UTC, gudmundurjon commented on Vinnusvæði/Verkþáttur 4/IOBWS-Claims3.0.yaml
> +  /v1/claims/{claimId}/primary:
Ég er aðeins að skoða þetta betur, Íslandsbanki lagði til að nota collection type name.

2021-12-16 15:29 UTC, merged

2021-12-17 11:26 UTC, gudnithor commented
Af hverju er búið að merge-a þessu? Átti ekki að klára að fara yfir þessar breytingar?

2021-12-17 11:38 UTC, asgeirh commented
Er þetta commit með öllum breytingum sem búið er að tala um í Bankahóp?
Eigum við að fara yfir þetta og vera með comments á fundinum í næstu viku?